name: Build & Push

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Build & Push API
        run: |
          IMAGE=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/api:latest
          docker build -f apps/api/Dockerfile -t $IMAGE .
          docker push $IMAGE

      - name: Build & Push ETL
        run: |
          IMAGE=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/etl:latest
          docker build -f apps/etl/Dockerfile -t $IMAGE .
          docker push $IMAGE

      - name: Build & Push train
        run: |
          IMAGE=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/train:latest
          docker build -f apps/train/Dockerfile -t $IMAGE .
          docker push $IMAGE

      - name: Build & Push forecast
        run: |
          IMAGE=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/forecast:latest
          docker build -f apps/forecast/Dockerfile -t $IMAGE apps/forecast/
          docker push $IMAGE

      - name: Update ETL Job
        run: |
          gcloud run jobs update etl-job \
            --image=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/etl:latest \
            --region=${{ vars.REGION }} \
            --update-env-vars RAW_DIR=/app/gcs/raw \
            --quiet

      - name: Update train Job
        run: |
          gcloud run jobs update train-job \
            --image=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/train:latest \
            --region=${{ vars.REGION }} \
            --update-env-vars RAW_DIR=/app/gcs/raw,MODELS_DIR=/app/gcs/models,PROCESSED_DIR=/app/gcs/processed,BQ_METRICS_TABLE=${{ vars.PROJECT }}.mspr_energie.model_runs \
            --quiet

      - name: Update forecast Job
        run: |
          gcloud run jobs update forecast \
            --image=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/forecast:latest \
            --region=${{ vars.REGION }} \
            --task-timeout=180 \
            --set-env-vars API_URL=https://api-s43aq3mwuq-ew.a.run.app,BQ_TABLE=${{ vars.PROJECT }}.mspr_energie.predictions \
            --quiet

      - name: Deploy API
        run: |
          gcloud run deploy api \
            --image=${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT }}/${{ vars.REPO }}/api:latest \
            --region=${{ vars.REGION }} \
            --update-env-vars RAW_DIR=/app/gcs/raw,MODELS_DIR=/app/gcs/models \
            --quiet

      - name: Deploy Workflow ETL-Forecast
        run: |
          gcloud workflows deploy etl-forecast \
            --source=workflows/etl_forecast.yaml \
            --location=${{ vars.REGION }} \
            --service-account=1087457673688-compute@developer.gserviceaccount.com \
            --quiet
